=== CrisDeboi/MyThings/Task de clase/pizzas.dtd
<!ELEMENT order (pizzas,adress,client)>
<!ELEMENT pizzas (pizza+)>
<!ELEMENT pizza (type,extraingredient*)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT extraingredient (#PCDATA)>
<!ELEMENT adress (street,number)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT client (name,surname)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

=== CrisDeboi/MyThings/Task de clase/pizzas.xml
<!DOCTYPE order SYSTEM "pizzas.dtd">
<order>
    <pizzas>
        <pizza>
            <type>Margarita</type>
            <extraingredient>pimientos morrones</extraingredient>
        </pizza>
        <pizza>
            <type>Artesana</type>
        </pizza>
        <pizza>
            <type>Artesana</type>
        </pizza>
        <pizza>
            <type>Vegetal</type>
        </pizza>

    </pizzas>
    <adress>
        <street>Guanarteme</street>
        <number>17</number>
    </adress>
    <client>
        <name>Pepe</name>
        <surname>Perez</surname>
    </client>
</order>
